---

- name: Copy the doftiles repo
  git:
    accept_hostkey: yes
    repo: git@github.com:giushansen/dotfiles_zsh.git
    dest: ~/dotfiles
    force: yes
    recursive: no

- name: Make sure the .zshrc file exists
  file:
    path: ~/.zshrc
    state: touch

- name: Load zshrc file into it
  blockinfile:
    path: ~/.zshrc
    block: |
      if [ -f ~/dotfiles/zshrc ]; then
        source ~/dotfiles/zshrc
      fi

- name: Make sure the .zprofile file exists
  file:
    path: ~/.zprofile
    state: touch
