---

- name: Install asdf
  homebrew:
    name: asdf
    state: latest

- name: Install node
  homebrew:
    name: node
    state: latest

- name: Install coreutils
  homebrew:
    name: coreutils
    state: latest

- name: Install bash
  homebrew:
    name: bash
    state: latest

- name: Install wget
  homebrew:
    name: wget
    state: latest
